### ISSUE TITLE
Cannot find namespace 'WebAssembly'.

### ISSUE THREAD

**Issue by craigphicks** [exuanbo/module-from-string#15]
After `yarn add module-from-string`and then trying to compile I get this error message:
```
node_modules/esbuild/lib/main.d.ts:582:16 - error TS2503: Cannot find namespace 'WebAssembly'.
582   wasmModule?: WebAssembly.Module
```
I'm using typescript 4.4.4, same as module-from-string 's devDependencies.

**Comment by exuanbo** [comment]
Could you provide a reproduction? I cannot reproduce the problem on my machine.

It seems `tsc` also checked type definition files. Set `skipLibCheck` to `true` in `compilerOptions` may help.

**Comment by craigphicks** [comment]
Confirmed your solution (`skipLibCheck:false`) works.
