### ISSUE TITLE
Cannot dynamically import in windows

### ISSUE THREAD

**Issue by matt-way** [exuanbo/module-from-string#17]
When trying to perform a dynamic import inside code imported using this lib, I get this error on windows:

`"Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'"`

However if I put the required `file:///` prefix it still fails because `path.resolve()` called inside `resolveModuleSpecifier` strips this away.

**Comment by exuanbo** [comment]
This should be fixed in new patch version `3.2.1`.
